// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, console} from "forge-std/Test.sol";
import {SpongefishWhirVerify} from "../src/spongefish/SpongefishWhirVerify.sol";
import {GoldilocksExt3} from "../src/spongefish/GoldilocksExt3.sol";
import {SumcheckBridgeVerifier} from "../src/spongefish/SumcheckBridgeVerifier.sol";
import {WhirPlonky2Verifier} from "../src/WhirPlonky2Verifier.sol";
import {GoldilocksField} from "../src/GoldilocksField.sol";

/// @title GenericE2ETest
/// @notice E2E test using a generic Poseidon hash-chain circuit (no intmax3 dependency).
///         Fixtures are generated by `cargo run --bin generate_fixture --release`.
///         Verifies WHIR polynomial commitment + Plonky2 constraint satisfaction on-chain.
contract GenericE2ETest is Test, WhirPlonky2Verifier {

    // =====================================================================
    // Fixture generation — generates if not present
    // =====================================================================

    function setUp() public {
        // Generate fixtures if not present.
        // Fixtures are produced by `cargo run --bin generate_fixture --release`
        // from the repo root. They are gitignored.
        if (!vm.isFile("test/data/test_constraint_data.json") || !vm.isFile("test/data/test_proof.json") || !vm.isFile("test/data/test_vk.json")) {
            // Use bash -c to cd to repo root and run cargo
            string[] memory cmd = new string[](3);
            cmd[0] = "bash";
            cmd[1] = "-c";
            cmd[2] = "cd .. && cargo +nightly run --bin generate_fixture --release 2>&1";
            vm.ffi(cmd);
        }
    }

    // =====================================================================
    // WHIR combined verification
    // =====================================================================

    function test_whir_combined() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        _verifyWhirCommitment(json);
    }

    // =====================================================================
    // Plonky2 constraint satisfaction
    // =====================================================================

    function test_plonky2_constraints() public {
        string memory json = vm.readFile("test/data/test_constraint_data.json");
        _verifyPlonky2Constraints(json);
    }

    // =====================================================================
    // Combined E2E
    // =====================================================================

    function test_full_e2e() public {
        string memory whirJson = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        string memory constraintJson = vm.readFile("test/data/test_constraint_data.json");

        // =====================================================================
        // Step 1: WHIR polynomial commitment verification (dual-point)
        // Proves: committed polynomial evaluates to f(r₁) and f(r₂) at
        //         sumcheck-derived points r₁ (for ζ) and r₂ (for gζ).
        // =====================================================================
        _verifyWhirCommitment(whirJson);
        console.log("[e2e] Step 1: WHIR dual-point verification PASSED");

        // =====================================================================
        // Step 2: Sumcheck bridge #1 (ζ) — binding WHIR to P(ζ)
        // Proves: ⟨f, h_ζ⟩ = P(ζ)  where f is the WHIR-committed polynomial
        // =====================================================================
        _verifySumcheckBridge(whirJson);
        console.log("[e2e] Step 2: Sumcheck bridge #1 (zeta) PASSED");

        // =====================================================================
        // Step 3: Sumcheck bridge #2 (gζ) — binding WHIR to P(gζ)
        // Proves: ⟨f, h_{gζ}⟩ = P(gζ)
        // =====================================================================
        _verifySumcheckBridgeGZeta(whirJson);
        console.log("[e2e] Step 3: Sumcheck bridge #2 (g*zeta) PASSED");

        // =====================================================================
        // Step 4: On-chain challenge derivation (from Merkle root)
        // Derives: betas, gammas, alphas, zeta — all bound to WHIR commitment
        // =====================================================================
        bytes memory transcript = vm.parseJsonBytes(whirJson, ".transcript");
        string memory sessionName = abi.decode(vm.parseJson(whirJson, ".session_name"), (string));
        uint256[] memory publicInputs = abi.decode(vm.parseJson(constraintJson, ".publicInputs"), (uint256[]));
        uint256 numChallenges = _u(constraintJson, ".circuitParams.numChallenges");

        (
            uint256[] memory betas,
            uint256[] memory gammas,
            uint256[] memory alphas,
            uint256 zetaC0,
            uint256 zetaC1,
            uint256 zetaC2
        ) = SumcheckBridgeVerifier.deriveKeccakChallengesV2(
            transcript, bytes(sessionName), publicInputs, numChallenges
        );
        console.log("[e2e] Step 4: On-chain challenge derivation DONE");

        // Steps 5-10: Decomposition, sub-decomposition, and constraint check
        // Split into separate function to avoid stack-too-deep
        {
            Challenges memory chal;
            chal.plonkBetas = betas;
            chal.plonkGammas = gammas;
            chal.plonkAlphas = alphas;
            chal.plonkZeta = GoldilocksExt3.Ext3(uint64(zetaC0), uint64(zetaC1), uint64(zetaC2));
            _verifyDecompositionAndConstraints(whirJson, constraintJson, chal, publicInputs);
        }
    }

    // =====================================================================
    // Unified verification with immutable VK
    // =====================================================================

    /// @notice Initialize VK from fixture, then verify proof.
    ///         VK is set once via initialize() and cannot be changed.
    function test_unified_verify() public {
        // Load and initialize VK (normally done at deployment, once per circuit)
        _initializeVK();

        // Load proof (changes per verification)
        string memory proofJson = vm.readFile("test/data/test_proof.json");
        Proof memory proof = _parseProof(proofJson);

        // Verify proof against stored VK
        bool valid = verify(proof);
        assertTrue(valid, "Unified WHIR-Plonky2 verification must pass");
    }

    /// @notice Gas measurement: parse proof only (delta = pure verify cost)
    function test_unified_parse_only() public {
        _initializeVK();
        string memory proofJson = vm.readFile("test/data/test_proof.json");
        Proof memory proof = _parseProof(proofJson);
        assertTrue(proof.transcript.length > 0);
    }

    bool private _vkInitialized;

    function _initializeVK() internal {
        if (_vkInitialized) return;
        _vkInitialized = true;

        string memory vkJson = vm.readFile("test/data/test_vk.json");
        CircuitConfig memory config = _parseCircuitConfig(vkJson);
        SpongefishWhirVerify.WhirParams memory whirParams = _loadWhirParamsFromVK(vkJson);
        bytes memory protocolId = vm.parseJsonBytes(vkJson, ".protocolId");
        bytes memory sessionId = vm.parseJsonBytes(vkJson, ".sessionId");
        bytes memory instance = vm.parseJsonBytes(vkJson, ".instance");

        this.initialize(config, whirParams, protocolId, sessionId, instance);
    }

    // =====================================================================
    // Standalone sumcheck bridge test
    // =====================================================================

    function test_sumcheck_bridge() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        _verifySumcheckBridge(json);
    }

    function test_challenge_derivation() public view {
        string memory whirJson = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        string memory constraintJson = vm.readFile("test/data/test_constraint_data.json");
        _verifyChallengeDerivation(whirJson, constraintJson);
    }

    function test_decomposition() public view {
        string memory whirJson = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        string memory constraintJson = vm.readFile("test/data/test_constraint_data.json");
        _verifyDecomposition(whirJson, constraintJson);
    }

    /// @notice Negative test: tampered claimed_sum must fail
    function test_sumcheck_bridge_tampered_claim() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        uint256 numRounds = _u(json, ".sumcheck.num_rounds");
        string memory sessionName = abi.decode(vm.parseJson(json, ".sumcheck.session_name"), (string));
        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.zeta.c0")),
            uint64(_u(json, ".sumcheck.zeta.c1")),
            uint64(_u(json, ".sumcheck.zeta.c2"))
        );
        // Tamper with claimed_sum: add 1 to c0
        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.claimed_sum.c0")) + 1,
            uint64(_u(json, ".sumcheck.claimed_sum.c1")),
            uint64(_u(json, ".sumcheck.claimed_sum.c2"))
        );
        GoldilocksExt3.Ext3[][] memory roundPolys = _parseSumcheckRoundPolys(json, numRounds);

        bool reverted = false;
        try this._externalVerifyBridge(numRounds, roundPolys, zeta, claimedSum, sessionName) {
            // Should not reach here
        } catch {
            reverted = true;
        }
        assertTrue(reverted, "tampered claimed_sum must revert");
    }

    /// @notice Negative test: tampered round polynomial must fail binding
    function test_sumcheck_bridge_tampered_roundpoly() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        uint256 numRounds = _u(json, ".sumcheck.num_rounds");
        string memory sessionName = abi.decode(vm.parseJson(json, ".sumcheck.session_name"), (string));
        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.zeta.c0")),
            uint64(_u(json, ".sumcheck.zeta.c1")),
            uint64(_u(json, ".sumcheck.zeta.c2"))
        );
        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.claimed_sum.c0")),
            uint64(_u(json, ".sumcheck.claimed_sum.c1")),
            uint64(_u(json, ".sumcheck.claimed_sum.c2"))
        );
        GoldilocksExt3.Ext3[][] memory roundPolys = _parseSumcheckRoundPolys(json, numRounds);

        // Tamper with g(2) in round 5
        roundPolys[5][2].c0 += 1;

        bool reverted = false;
        try this._externalVerifyBridge(numRounds, roundPolys, zeta, claimedSum, sessionName) {
            // Should not reach here
        } catch {
            reverted = true;
        }
        assertTrue(reverted, "tampered round polynomial must revert");
    }

    /// @dev External wrapper for try/catch (internal library calls can't be caught)
    function _externalVerifyBridge(
        uint256 numRounds,
        GoldilocksExt3.Ext3[][] memory roundPolys,
        GoldilocksExt3.Ext3 memory zeta,
        GoldilocksExt3.Ext3 memory claimedSum,
        string memory sessionName
    ) external pure {
        SumcheckBridgeVerifier.verify(numRounds, roundPolys, zeta, claimedSum, sessionName);
    }

    // =====================================================================
    // Internal: Sumcheck bridge verification
    // =====================================================================

    function _verifySumcheckBridge(string memory json) internal pure {
        // Parse sumcheck proof data
        uint256 numRounds = _u(json, ".sumcheck.num_rounds");
        string memory sessionName = abi.decode(vm.parseJson(json, ".sumcheck.session_name"), (string));

        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.zeta.c0")),
            uint64(_u(json, ".sumcheck.zeta.c1")),
            uint64(_u(json, ".sumcheck.zeta.c2"))
        );

        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.claimed_sum.c0")),
            uint64(_u(json, ".sumcheck.claimed_sum.c1")),
            uint64(_u(json, ".sumcheck.claimed_sum.c2"))
        );

        // Parse round polynomials
        GoldilocksExt3.Ext3[][] memory roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(
                    ".sumcheck.round_polys[", vm.toString(i), "][", vm.toString(j), "]."
                );
                roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }

        // Verify sumcheck: derive evalPoint and finalClaim
        (
            GoldilocksExt3.Ext3[] memory evalPoint,
            GoldilocksExt3.Ext3 memory finalClaim
        ) = SumcheckBridgeVerifier.verify(numRounds, roundPolys, zeta, claimedSum, sessionName);

        // Verify that derived evalPoint matches the one passed to WHIR
        for (uint256 i = 0; i < numRounds; i++) {
            string memory epPrefix = string.concat(".evaluation_point[", vm.toString(i), "].");
            uint64 ec0 = uint64(_u(json, string.concat(epPrefix, "c0")));
            uint64 ec1 = uint64(_u(json, string.concat(epPrefix, "c1")));
            uint64 ec2 = uint64(_u(json, string.concat(epPrefix, "c2")));
            require(
                evalPoint[i].c0 == ec0 && evalPoint[i].c1 == ec1 && evalPoint[i].c2 == ec2,
                string.concat("evalPoint mismatch at round ", vm.toString(i))
            );
        }

        // Compute h_ζ(r)
        GoldilocksExt3.Ext3 memory hZetaAtR = SumcheckBridgeVerifier.computeHZeta(zeta, evalPoint);

        // Get WHIR evaluation f(r) from fixture
        GoldilocksExt3.Ext3 memory whirEvalAtR = GoldilocksExt3.Ext3(
            uint64(_u(json, ".evaluations[0].c0")),
            uint64(_u(json, ".evaluations[0].c1")),
            uint64(_u(json, ".evaluations[0].c2"))
        );

        // Verify binding: f(r) · h_ζ(r) == finalClaim
        SumcheckBridgeVerifier.verifyBinding(whirEvalAtR, hZetaAtR, finalClaim);
    }

    // =====================================================================
    // Internal: Challenge re-derivation (Issue 1 fix)
    // =====================================================================

    function _verifyChallengeDerivation(string memory whirJson, string memory constraintJson) internal pure {
        bytes memory transcript = vm.parseJsonBytes(whirJson, ".transcript");
        string memory sessionName = abi.decode(vm.parseJson(whirJson, ".session_name"), (string));
        uint256[] memory publicInputs = abi.decode(vm.parseJson(constraintJson, ".publicInputs"), (uint256[]));
        uint256 numChallenges = _u(constraintJson, ".circuitParams.numChallenges");

        // Derive challenges on-chain (v2: from Merkle root instead of full transcript)
        (
            uint256[] memory betas,
            uint256[] memory gammas,
            uint256[] memory alphas,
            uint256 zetaC0,
            uint256 zetaC1,
            uint256 zetaC2
        ) = SumcheckBridgeVerifier.deriveKeccakChallengesV2(
            transcript, bytes(sessionName), publicInputs, numChallenges
        );

        // Compare with fixture values
        uint256[] memory expectedBetas = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkBetas"), (uint256[]));
        uint256[] memory expectedGammas = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkGammas"), (uint256[]));
        uint256[] memory expectedAlphas = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkAlphas"), (uint256[]));
        uint256[] memory expectedZeta = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkZeta"), (uint256[]));

        for (uint256 i = 0; i < numChallenges; i++) {
            require(betas[i] == expectedBetas[i], "beta mismatch");
            require(gammas[i] == expectedGammas[i], "gamma mismatch");
            require(alphas[i] == expectedAlphas[i], "alpha mismatch");
        }
        require(zetaC0 == expectedZeta[0], "zeta.c0 mismatch");
        require(zetaC1 == expectedZeta[1], "zeta.c1 mismatch");
        require(zetaC2 == expectedZeta[2], "zeta.c2 mismatch");
    }

    // =====================================================================
    // Internal: Decomposition check (Issue 2 fix)
    // =====================================================================

    function _verifyDecomposition(string memory whirJson, string memory constraintJson) internal pure {
        // Get claimed_sum from sumcheck
        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(whirJson, ".sumcheck.claimed_sum.c0")),
            uint64(_u(whirJson, ".sumcheck.claimed_sum.c1")),
            uint64(_u(whirJson, ".sumcheck.claimed_sum.c2"))
        );

        // Get sumcheck zeta
        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(whirJson, ".sumcheck.zeta.c0")),
            uint64(_u(whirJson, ".sumcheck.zeta.c1")),
            uint64(_u(whirJson, ".sumcheck.zeta.c2"))
        );

        // Get batch sizes
        uint256[] memory batchSizes = abi.decode(vm.parseJson(constraintJson, ".batchSizes"), (uint256[]));

        // Get batch evaluations at sumcheck.zeta
        uint256 nBatches = batchSizes.length;
        GoldilocksExt3.Ext3[] memory batchEvals = new GoldilocksExt3.Ext3[](nBatches);
        for (uint256 i = 0; i < nBatches; i++) {
            string memory prefix = string.concat(".batchEvalsAtZeta[", vm.toString(i), "].");
            batchEvals[i] = GoldilocksExt3.Ext3(
                uint64(_u(constraintJson, string.concat(prefix, "c0"))),
                uint64(_u(constraintJson, string.concat(prefix, "c1"))),
                uint64(_u(constraintJson, string.concat(prefix, "c2")))
            );
        }

        // Verify: P(ζ) = Σ batch_i(ζ) · ζ^offset_i
        SumcheckBridgeVerifier.verifyDecomposition(claimedSum, batchSizes, zeta, batchEvals);
    }

    // =====================================================================
    // Internal: WHIR commitment verification
    // =====================================================================

    function _verifyWhirCommitment(string memory json) internal pure {
        bytes memory protocolId = vm.parseJsonBytes(json, ".protocol_id");
        bytes memory sessionId = vm.parseJsonBytes(json, ".session_id");
        bytes memory instance = vm.parseJsonBytes(json, ".instance");
        bytes memory transcript = vm.parseJsonBytes(json, ".transcript");
        bytes memory hints = vm.parseJsonBytes(json, ".hints");

        // Load all evaluations (1 for single-point, 2 for dual-point with gζ bridge)
        uint256 numEvals = 2; // dual-point mode
        GoldilocksExt3.Ext3[] memory evaluations = new GoldilocksExt3.Ext3[](numEvals);
        for (uint256 i = 0; i < numEvals; i++) {
            string memory prefix = string.concat(".evaluations[", vm.toString(i), "].");
            evaluations[i] = GoldilocksExt3.Ext3(
                uint64(_u(json, string.concat(prefix, "c0"))),
                uint64(_u(json, string.concat(prefix, "c1"))),
                uint64(_u(json, string.concat(prefix, "c2")))
            );
        }

        SpongefishWhirVerify.WhirParams memory params = _loadParams(json);

        bool valid = SpongefishWhirVerify.verifyWhirProof(
            protocolId, sessionId, instance, transcript, hints, evaluations, params
        );
        assertTrue(valid, "WHIR combined must verify");
    }

    // =====================================================================
    // Internal: Plonky2 constraint verification
    // =====================================================================

    function _verifyPlonky2Constraints(string memory json) internal {
        CircuitParams memory params;
        params.degreeBits = abi.decode(vm.parseJson(json, ".circuitParams.degreeBits"), (uint256));
        params.numChallenges = abi.decode(vm.parseJson(json, ".circuitParams.numChallenges"), (uint256));
        params.numRoutedWires = abi.decode(vm.parseJson(json, ".circuitParams.numRoutedWires"), (uint256));
        params.quotientDegreeFactor = abi.decode(vm.parseJson(json, ".circuitParams.quotientDegreeFactor"), (uint256));
        params.numPartialProducts = abi.decode(vm.parseJson(json, ".circuitParams.numPartialProducts"), (uint256));
        params.numGateConstraints = abi.decode(vm.parseJson(json, ".circuitParams.numGateConstraints"), (uint256));
        params.numSelectors = abi.decode(vm.parseJson(json, ".circuitParams.numSelectors"), (uint256));
        params.numLookupSelectors = abi.decode(vm.parseJson(json, ".circuitParams.numLookupSelectors"), (uint256));

        uint256[] memory constFlat = abi.decode(vm.parseJson(json, ".openings.constants"), (uint256[]));
        uint256[] memory sigmaFlat = abi.decode(vm.parseJson(json, ".openings.plonkSigmas"), (uint256[]));
        uint256[] memory wiresFlat = abi.decode(vm.parseJson(json, ".openings.wires"), (uint256[]));
        uint256[] memory zsFlat = abi.decode(vm.parseJson(json, ".openings.plonkZs"), (uint256[]));
        uint256[] memory zsNextFlat = abi.decode(vm.parseJson(json, ".openings.plonkZsNext"), (uint256[]));
        uint256[] memory ppFlat = abi.decode(vm.parseJson(json, ".openings.partialProducts"), (uint256[]));
        uint256[] memory qpFlat = abi.decode(vm.parseJson(json, ".openings.quotientPolys"), (uint256[]));

        Openings memory openings;
        // TODO: Fixture JSON still stores openings as flat Ext2 pairs [c0, c1, ...].
        // When the Rust exporter is updated for Ext3, switch _flatToExt3 to read triplets.
        openings.constants = _flatToExt3(constFlat);
        openings.plonkSigmas = _flatToExt3(sigmaFlat);
        openings.wires = _flatToExt3(wiresFlat);
        openings.plonkZs = _flatToExt3(zsFlat);
        openings.plonkZsNext = _flatToExt3(zsNextFlat);
        openings.partialProducts = _flatToExt3(ppFlat);
        openings.quotientPolys = _flatToExt3(qpFlat);

        Challenges memory challenges;
        challenges.plonkBetas = abi.decode(vm.parseJson(json, ".challenges.plonkBetas"), (uint256[]));
        challenges.plonkGammas = abi.decode(vm.parseJson(json, ".challenges.plonkGammas"), (uint256[]));
        challenges.plonkAlphas = abi.decode(vm.parseJson(json, ".challenges.plonkAlphas"), (uint256[]));
        {
            uint256[] memory zetaFlat = abi.decode(vm.parseJson(json, ".challenges.plonkZeta"), (uint256[]));
            challenges.plonkZeta = GoldilocksExt3.Ext3(uint64(zetaFlat[0]), uint64(zetaFlat[1]), uint64(zetaFlat[2]));
        }

        PermutationData memory permData;
        permData.kIs = abi.decode(vm.parseJson(json, ".permutation.kIs"), (uint256[]));

        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".gates..gateType"), (uint256[]));
        GateInfo[] memory gates = _parseGates(json, gateTypes.length);

        uint256[] memory publicInputs = abi.decode(vm.parseJson(json, ".publicInputs"), (uint256[]));

        bool valid = verifyConstraints(openings, params, challenges, permData, gates, publicInputs);
        assertTrue(valid, "Plonky2 constraint verification must pass");
    }

    // =====================================================================
    // Internal: Full decomposition + constraint verification (Steps 5-10)
    // Split from test_full_e2e to avoid stack-too-deep.
    // =====================================================================

    function _verifyDecompositionAndConstraints(
        string memory whirJson,
        string memory constraintJson,
        Challenges memory chal,
        uint256[] memory publicInputs
    ) internal {
        uint256[] memory batchSizes = abi.decode(vm.parseJson(constraintJson, ".batchSizes"), (uint256[]));
        uint256[] memory polyCounts = abi.decode(vm.parseJson(constraintJson, ".intraBatchPolyCounts"), (uint256[]));
        uint256 polyDegree = 1 << _u(constraintJson, ".circuitParams.degreeBits");

        GoldilocksExt3.Ext3 memory zetaExt3 = GoldilocksExt3.Ext3(
            uint64(_u(whirJson, ".sumcheck.zeta.c0")),
            uint64(_u(whirJson, ".sumcheck.zeta.c1")),
            uint64(_u(whirJson, ".sumcheck.zeta.c2"))
        );

        // =====================================================================
        // Step 5: Recomposition at ζ (replaces inter-batch + intra-batch decomp)
        // Single check: P(ζ) == Σ_j opening_j · ζ^{offset_j}
        // =====================================================================
        {
            GoldilocksExt3.Ext3[] memory allOpenings = _loadAllOpenings(constraintJson, polyCounts);
            GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
                uint64(_u(whirJson, ".sumcheck.claimed_sum.c0")),
                uint64(_u(whirJson, ".sumcheck.claimed_sum.c1")),
                uint64(_u(whirJson, ".sumcheck.claimed_sum.c2"))
            );
            SumcheckBridgeVerifier.verifyRecomposition(claimedSum, batchSizes, polyCounts, polyDegree, zetaExt3, allOpenings);
        }
        console.log("[e2e] Step 5: Recomposition at zeta PASSED");

        // =====================================================================
        // Step 6: gζ — inter-batch decomposition + batch 2 sub-decomposition
        // gζ has no constraint check, so batch 2 needs explicit sub-decomp
        // =====================================================================
        GoldilocksExt3.Ext3 memory gZetaExt3 = GoldilocksExt3.Ext3(
            uint64(_u(whirJson, ".sumcheck_g_zeta.g_zeta.c0")),
            uint64(_u(whirJson, ".sumcheck_g_zeta.g_zeta.c1")),
            uint64(_u(whirJson, ".sumcheck_g_zeta.g_zeta.c2"))
        );
        GoldilocksExt3.Ext3[] memory batchEvalsGZ;
        {
            uint256[] memory flat = abi.decode(vm.parseJson(constraintJson, ".batchEvalsAtGZetaFlat"), (uint256[]));
            uint256 nb = batchSizes.length;
            batchEvalsGZ = new GoldilocksExt3.Ext3[](nb);
            for (uint256 i = 0; i < nb; i++) {
                batchEvalsGZ[i] = GoldilocksExt3.Ext3(uint64(flat[i*3]), uint64(flat[i*3+1]), uint64(flat[i*3+2]));
            }
        }
        {
            GoldilocksExt3.Ext3 memory claimedSumGZ = GoldilocksExt3.Ext3(
                uint64(_u(whirJson, ".sumcheck_g_zeta.claimed_sum.c0")),
                uint64(_u(whirJson, ".sumcheck_g_zeta.claimed_sum.c1")),
                uint64(_u(whirJson, ".sumcheck_g_zeta.claimed_sum.c2"))
            );
            SumcheckBridgeVerifier.verifyDecomposition(claimedSumGZ, batchSizes, gZetaExt3, batchEvalsGZ);
        }
        GoldilocksExt3.Ext3[] memory batch2PolyEvalsGZ;
        {
            uint256[] memory flat = abi.decode(vm.parseJson(constraintJson, ".batch2EvalsAtGZetaFlat"), (uint256[]));
            uint256 n2 = polyCounts[2];
            batch2PolyEvalsGZ = new GoldilocksExt3.Ext3[](n2);
            for (uint256 j = 0; j < n2; j++) {
                batch2PolyEvalsGZ[j] = GoldilocksExt3.Ext3(uint64(flat[j*3]), uint64(flat[j*3+1]), uint64(flat[j*3+2]));
            }
        }
        SumcheckBridgeVerifier.verifySubDecomposition(batchEvalsGZ[2], polyDegree, gZetaExt3, batch2PolyEvalsGZ);
        console.log("[e2e] Step 6: g*zeta decomposition + batch2 sub-decomp PASSED");

        // Step 7-8: Build verified openings and check constraints
        _buildOpeningsAndVerifyConstraints(
            constraintJson, polyCounts, batch2PolyEvalsGZ,
            chal, publicInputs
        );
    }

    function _buildOpeningsAndVerifyConstraints(
        string memory constraintJson,
        uint256[] memory polyCounts,
        GoldilocksExt3.Ext3[] memory batch2PolyEvalsGZ,
        Challenges memory chal,
        uint256[] memory publicInputs
    ) internal {
        uint256 numChallenges = chal.plonkBetas.length;
        // Load per-polynomial evals for each batch at ζ (bulk decode from flat arrays)
        GoldilocksExt3.Ext3[] memory b0evals = _loadBatchEvalsFlat(constraintJson, 0, polyCounts[0]);
        GoldilocksExt3.Ext3[] memory b1evals = _loadBatchEvalsFlat(constraintJson, 1, polyCounts[1]);
        GoldilocksExt3.Ext3[] memory b2evals = _loadBatchEvalsFlat(constraintJson, 2, polyCounts[2]);
        GoldilocksExt3.Ext3[] memory b3evals = _loadBatchEvalsFlat(constraintJson, 3, polyCounts[3]);

        uint256 numRoutedWires = _u(constraintJson, ".circuitParams.numRoutedWires");
        uint256 numPartialProducts = _u(constraintJson, ".circuitParams.numPartialProducts");

        // Build Openings from verified sub-decomposed Ext3 evaluations (already Ext3)
        Openings memory openings;

        // batch 0: constants then plonkSigmas
        {
            uint256 numSigmaPolys = numRoutedWires;
            uint256 numConstantEntries = polyCounts[0] - numSigmaPolys;
            openings.constants = new GoldilocksExt3.Ext3[](numConstantEntries);
            for (uint256 i = 0; i < numConstantEntries; i++) {
                openings.constants[i] = b0evals[i];
            }
            openings.plonkSigmas = new GoldilocksExt3.Ext3[](numSigmaPolys);
            for (uint256 i = 0; i < numSigmaPolys; i++) {
                openings.plonkSigmas[i] = b0evals[numConstantEntries + i];
            }
        }

        // batch 1: wires
        openings.wires = new GoldilocksExt3.Ext3[](polyCounts[1]);
        for (uint256 i = 0; i < polyCounts[1]; i++) {
            openings.wires[i] = b1evals[i];
        }

        // batch 2: [Z, partialProducts...] per challenge + Z(gζ)
        {
            uint256 stride = 1 + numPartialProducts;
            openings.plonkZs = new GoldilocksExt3.Ext3[](numChallenges);
            openings.partialProducts = new GoldilocksExt3.Ext3[](numChallenges * numPartialProducts);
            openings.plonkZsNext = new GoldilocksExt3.Ext3[](numChallenges);
            for (uint256 ch = 0; ch < numChallenges; ch++) {
                openings.plonkZs[ch] = b2evals[ch * stride];
                for (uint256 pp = 0; pp < numPartialProducts; pp++) {
                    openings.partialProducts[ch * numPartialProducts + pp] = b2evals[ch * stride + 1 + pp];
                }
                openings.plonkZsNext[ch] = batch2PolyEvalsGZ[ch * stride];
            }
        }

        // batch 3: quotient chunks
        openings.quotientPolys = new GoldilocksExt3.Ext3[](polyCounts[3]);
        for (uint256 i = 0; i < polyCounts[3]; i++) {
            openings.quotientPolys[i] = b3evals[i];
        }
        console.log("[e2e] Step 9: Verified Openings built from sub-decomposition");

        // Step 10: Plonky2 constraint check with FULLY VERIFIED data
        CircuitParams memory params;
        params.degreeBits = _u(constraintJson, ".circuitParams.degreeBits");
        params.numChallenges = numChallenges;
        params.numRoutedWires = numRoutedWires;
        params.quotientDegreeFactor = _u(constraintJson, ".circuitParams.quotientDegreeFactor");
        params.numPartialProducts = numPartialProducts;
        params.numGateConstraints = _u(constraintJson, ".circuitParams.numGateConstraints");
        params.numSelectors = _u(constraintJson, ".circuitParams.numSelectors");
        params.numLookupSelectors = _u(constraintJson, ".circuitParams.numLookupSelectors");

        PermutationData memory permData;
        permData.kIs = abi.decode(vm.parseJson(constraintJson, ".permutation.kIs"), (uint256[]));

        GateInfo[] memory gates = _parseGates(constraintJson,
            abi.decode(vm.parseJson(constraintJson, ".gates..gateType"), (uint256[])).length
        );

        bool valid = verifyConstraints(openings, params, chal, permData, gates, publicInputs);
        assertTrue(valid, "Plonky2 constraint verification with verified openings must pass");
        console.log("[e2e] Step 10: Plonky2 constraints with VERIFIED openings PASSED");
    }

    // =====================================================================
    // Helpers
    // =====================================================================

    function _loadParams(string memory json) internal pure returns (SpongefishWhirVerify.WhirParams memory p) {
        p.numVariables = _u(json, ".whir_params.num_variables");
        p.foldingFactor = _u(json, ".whir_params.folding_factor");
        p.numVectors = _u(json, ".whir_params.num_vectors");
        p.outDomainSamples = _u(json, ".whir_params.out_domain_samples");
        p.inDomainSamples = _u(json, ".whir_params.in_domain_samples");
        p.initialSumcheckRounds = _u(json, ".whir_params.initial_sumcheck_rounds");
        p.numRounds = _u(json, ".whir_params.num_rounds");
        p.finalSumcheckRounds = _u(json, ".whir_params.final_sumcheck_rounds");
        p.finalSize = _u(json, ".whir_params.final_size");
        p.initialCodewordLength = _u(json, ".whir_params.initial_codeword_length");
        p.initialMerkleDepth = _u(json, ".whir_params.initial_merkle_depth");
        p.initialDomainGenerator = uint64(_u(json, ".whir_params.initial_domain_generator"));
        p.initialInterleavingDepth = _u(json, ".whir_params.initial_interleaving_depth");
        p.initialNumVariables = _u(json, ".whir_params.initial_num_variables");
        p.initialCosetSize = _u(json, ".whir_params.initial_coset_size");
        p.initialNumCosets = _u(json, ".whir_params.initial_num_cosets");

        // Load evaluation point r₁ (sumcheck-derived, or empty for canonical)
        {
            uint256 nv = p.numVariables;
            p.evaluationPoint = new GoldilocksExt3.Ext3[](nv);
            for (uint256 i = 0; i < nv; i++) {
                string memory epPrefix = string.concat(".evaluation_point[", vm.toString(i), "].");
                uint64 c0 = uint64(_u(json, string.concat(epPrefix, "c0")));
                uint64 c1 = uint64(_u(json, string.concat(epPrefix, "c1")));
                uint64 c2 = uint64(_u(json, string.concat(epPrefix, "c2")));
                p.evaluationPoint[i] = GoldilocksExt3.Ext3(c0, c1, c2);
            }
        }

        // Load second evaluation point r₂ (for dual-point / gζ bridge)
        // This is in the sumcheck_g_zeta section of the WHIR verifier data
        {
            // Check if sumcheck_g_zeta.eval_point exists
            bytes memory rawEp2 = vm.parseJson(json, ".sumcheck_g_zeta.eval_point");
            if (rawEp2.length > 0) {
                uint256 nv = p.numVariables;
                p.evaluationPoint2 = new GoldilocksExt3.Ext3[](nv);
                for (uint256 i = 0; i < nv; i++) {
                    string memory epPrefix = string.concat(".sumcheck_g_zeta.eval_point[", vm.toString(i), "].");
                    uint64 c0 = uint64(_u(json, string.concat(epPrefix, "c0")));
                    uint64 c1 = uint64(_u(json, string.concat(epPrefix, "c1")));
                    uint64 c2 = uint64(_u(json, string.concat(epPrefix, "c2")));
                    p.evaluationPoint2[i] = GoldilocksExt3.Ext3(c0, c1, c2);
                }
            }
        }

        p.rounds = new SpongefishWhirVerify.RoundParams[](p.numRounds);
        for (uint256 i = 0; i < p.numRounds; i++) {
            string memory prefix = string.concat(".whir_params.rounds[", vm.toString(i), "].");
            p.rounds[i].codewordLength = _u(json, string.concat(prefix, "codeword_length"));
            p.rounds[i].merkleDepth = _u(json, string.concat(prefix, "merkle_depth"));
            p.rounds[i].domainGenerator = uint64(_u(json, string.concat(prefix, "domain_generator")));
            p.rounds[i].inDomainSamples = _u(json, string.concat(prefix, "in_domain_samples"));
            p.rounds[i].outDomainSamples = _u(json, string.concat(prefix, "out_domain_samples"));
            p.rounds[i].sumcheckRounds = _u(json, string.concat(prefix, "sumcheck_rounds"));
            p.rounds[i].interleavingDepth = _u(json, string.concat(prefix, "interleaving_depth"));
            p.rounds[i].cosetSize = _u(json, string.concat(prefix, "coset_size"));
            p.rounds[i].numCosets = _u(json, string.concat(prefix, "num_cosets"));
            p.rounds[i].numVariables = _u(json, string.concat(prefix, "num_variables"));
        }
    }

    function _parseSumcheckRoundPolys(string memory json, uint256 numRounds)
        internal pure returns (GoldilocksExt3.Ext3[][] memory roundPolys)
    {
        roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(
                    ".sumcheck.round_polys[", vm.toString(i), "][", vm.toString(j), "]."
                );
                roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }
    }

    function _u(string memory json, string memory path) internal pure returns (uint256) {
        return abi.decode(vm.parseJson(json, path), (uint256));
    }

    /// @dev Convert flat u64 array [c0, c1, c0, c1, ...] (Ext2 format) to Ext3 with c2=0.
    /// TODO: When the Rust exporter outputs Ext3 triplets [c0, c1, c2, ...], update to read 3 per element.
    function _flatToExt3(uint256[] memory flat) internal pure returns (GoldilocksExt3.Ext3[] memory) {
        uint256 len = flat.length / 2;
        GoldilocksExt3.Ext3[] memory result = new GoldilocksExt3.Ext3[](len);
        for (uint256 i = 0; i < len; i++) {
            result[i] = GoldilocksExt3.Ext3(uint64(flat[i * 2]), uint64(flat[i * 2 + 1]), 0);
        }
        return result;
    }

    function _parseGates(string memory json, uint256 numGates)
        internal pure returns (GateInfo[] memory)
    {
        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".gates..gateType"), (uint256[]));
        uint256[] memory selectorIndices = abi.decode(vm.parseJson(json, ".gates..selectorIndex"), (uint256[]));
        uint256[] memory groupStarts = abi.decode(vm.parseJson(json, ".gates..groupStart"), (uint256[]));
        uint256[] memory groupEnds = abi.decode(vm.parseJson(json, ".gates..groupEnd"), (uint256[]));
        uint256[] memory rowInGroups = abi.decode(vm.parseJson(json, ".gates..rowInGroup"), (uint256[]));
        uint256[] memory numConstraintsList = abi.decode(vm.parseJson(json, ".gates..numConstraints"), (uint256[]));

        GateInfo[] memory gates = new GateInfo[](numGates);
        for (uint256 i = 0; i < numGates; i++) {
            // Parse gateConfig from JSON
            string memory cfgKey = string.concat(".gates[", vm.toString(i), "].gateConfig");
            uint256[] memory config = abi.decode(vm.parseJson(json, cfgKey), (uint256[]));
            gates[i] = GateInfo(
                gateTypes[i], selectorIndices[i], groupStarts[i],
                groupEnds[i], rowInGroups[i], numConstraintsList[i],
                config
            );
        }
        return gates;
    }

    /// @dev Parse an array of Ext3 values from JSON at a given path prefix.
    /// @dev Load per-polynomial evals for one batch from flat uint256 array.
    function _loadBatchEvalsFlat(string memory json, uint256 batchIdx, uint256 count)
        internal pure returns (GoldilocksExt3.Ext3[] memory result)
    {
        string memory path = string.concat(".intraBatchEvalsAtZetaFlat[", vm.toString(batchIdx), "]");
        uint256[] memory flat = abi.decode(vm.parseJson(json, path), (uint256[]));
        result = new GoldilocksExt3.Ext3[](count);
        for (uint256 j = 0; j < count; j++) {
            result[j] = GoldilocksExt3.Ext3(uint64(flat[j*3]), uint64(flat[j*3+1]), uint64(flat[j*3+2]));
        }
    }

    /// @dev Load all individual polynomial openings across all batches into a flat array.
    ///      Uses bulk abi.decode to avoid per-element vm.parseJson overhead.
    function _loadAllOpenings(string memory json, uint256[] memory polyCounts)
        internal pure returns (GoldilocksExt3.Ext3[] memory allOpenings)
    {
        uint256 total = 0;
        for (uint256 b = 0; b < polyCounts.length; b++) total += polyCounts[b];
        allOpenings = new GoldilocksExt3.Ext3[](total);
        uint256 idx = 0;
        for (uint256 b = 0; b < polyCounts.length; b++) {
            // Bulk decode: parse the entire batch array at once as flat uint256[]
            // Each Ext3 element is stored as {c0, c1, c2} object in JSON.
            // We decode the entire sub-array and extract c0/c1/c2 per element.
            string memory batchPath = string.concat(".intraBatchEvalsAtZetaFlat[", vm.toString(b), "]");
            uint256[] memory flat = abi.decode(vm.parseJson(json, batchPath), (uint256[]));
            for (uint256 j = 0; j < polyCounts[b]; j++) {
                allOpenings[idx++] = GoldilocksExt3.Ext3(
                    uint64(flat[j * 3]),
                    uint64(flat[j * 3 + 1]),
                    uint64(flat[j * 3 + 2])
                );
            }
        }
    }

    function _parseExt3Array(string memory json, string memory arrayPath, uint256 count)
        internal pure returns (GoldilocksExt3.Ext3[] memory result)
    {
        result = new GoldilocksExt3.Ext3[](count);
        for (uint256 i = 0; i < count; i++) {
            string memory prefix = string.concat(arrayPath, "[", vm.toString(i), "].");
            result[i] = GoldilocksExt3.Ext3(
                uint64(_u(json, string.concat(prefix, "c0"))),
                uint64(_u(json, string.concat(prefix, "c1"))),
                uint64(_u(json, string.concat(prefix, "c2")))
            );
        }
    }

    /// @dev Verify sumcheck bridge #2 for g*zeta.
    function _verifySumcheckBridgeGZeta(string memory json) internal pure {
        uint256 numRounds = _u(json, ".sumcheck_g_zeta.num_rounds");
        string memory sessionName = abi.decode(vm.parseJson(json, ".sumcheck.session_name"), (string));

        GoldilocksExt3.Ext3 memory gZeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck_g_zeta.g_zeta.c0")),
            uint64(_u(json, ".sumcheck_g_zeta.g_zeta.c1")),
            uint64(_u(json, ".sumcheck_g_zeta.g_zeta.c2"))
        );

        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck_g_zeta.claimed_sum.c0")),
            uint64(_u(json, ".sumcheck_g_zeta.claimed_sum.c1")),
            uint64(_u(json, ".sumcheck_g_zeta.claimed_sum.c2"))
        );

        // Parse round polynomials for g*zeta sumcheck
        GoldilocksExt3.Ext3[][] memory roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(
                    ".sumcheck_g_zeta.round_polys[", vm.toString(i), "][", vm.toString(j), "]."
                );
                roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }

        // Verify sumcheck #2: using "sumcheck-challenges-gzeta" domain separation tag
        (
            GoldilocksExt3.Ext3[] memory evalPoint2,
            GoldilocksExt3.Ext3 memory finalClaim2
        ) = SumcheckBridgeVerifier.verifyWithTag(
            numRounds, roundPolys, gZeta, claimedSum, sessionName, "sumcheck-challenges-gzeta"
        );

        // Verify evalPoint2 matches fixture
        for (uint256 i = 0; i < numRounds; i++) {
            string memory epPrefix = string.concat(".sumcheck_g_zeta.eval_point[", vm.toString(i), "].");
            uint64 ec0 = uint64(_u(json, string.concat(epPrefix, "c0")));
            uint64 ec1 = uint64(_u(json, string.concat(epPrefix, "c1")));
            uint64 ec2 = uint64(_u(json, string.concat(epPrefix, "c2")));
            require(
                evalPoint2[i].c0 == ec0 && evalPoint2[i].c1 == ec1 && evalPoint2[i].c2 == ec2,
                string.concat("evalPoint2 mismatch at round ", vm.toString(i))
            );
        }

        // Compute h_{gζ}(r₂) and verify binding
        GoldilocksExt3.Ext3 memory hGZetaAtR2 = SumcheckBridgeVerifier.computeHZeta(gZeta, evalPoint2);

        GoldilocksExt3.Ext3 memory whirEvalAtR2 = GoldilocksExt3.Ext3(
            uint64(_u(json, ".evaluations[1].c0")),
            uint64(_u(json, ".evaluations[1].c1")),
            uint64(_u(json, ".evaluations[1].c2"))
        );

        SumcheckBridgeVerifier.verifyBinding(whirEvalAtR2, hGZetaAtR2, finalClaim2);
    }

    // =====================================================================
    // Unified proof parsing helpers
    // =====================================================================

    /// @dev Parse proof from proof-only JSON (test_proof.json, no .proof prefix)
    function _parseProof(string memory json)
        internal view returns (Proof memory proof)
    {
        proof.transcript = vm.parseJsonBytes(json, ".transcript");
        proof.hints = vm.parseJsonBytes(json, ".hints");

        proof.evaluations = new GoldilocksExt3.Ext3[](2);
        for (uint256 i = 0; i < 2; i++) {
            string memory prefix = string.concat(".evaluations[", vm.toString(i), "].");
            proof.evaluations[i] = GoldilocksExt3.Ext3(
                uint64(_u(json, string.concat(prefix, "c0"))),
                uint64(_u(json, string.concat(prefix, "c1"))),
                uint64(_u(json, string.concat(prefix, "c2")))
            );
        }

        proof.bridgeZeta = _parseBridgeZetaDirect(json);
        proof.bridgeGZeta = _parseBridgeGZetaDirect(json);

        // polyCounts from VK (already stored in contract)
        uint256[] memory polyCounts = _circuitConfig.intraBatchPolyCounts;
        proof.allOpeningsAtZetaFlat = new uint256[][](polyCounts.length);
        for (uint256 b = 0; b < polyCounts.length; b++) {
            string memory path = string.concat(".allOpeningsAtZetaFlat[", vm.toString(b), "]");
            proof.allOpeningsAtZetaFlat[b] = abi.decode(vm.parseJson(json, path), (uint256[]));
        }

        proof.batch2OpeningsAtGZetaFlat = abi.decode(vm.parseJson(json, ".batch2OpeningsAtGZetaFlat"), (uint256[]));
        proof.batchEvalsAtGZetaFlat = abi.decode(vm.parseJson(json, ".batchEvalsAtGZetaFlat"), (uint256[]));
        proof.publicInputs = abi.decode(vm.parseJson(json, ".publicInputs"), (uint256[]));
    }

    function _parseBridgeZetaDirect(string memory json)
        internal pure returns (SumcheckBridgeData memory bridge)
    {
        uint256 numRounds = _u(json, ".bridgeZeta.numRounds");
        bridge.zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".bridgeZeta.zeta.c0")),
            uint64(_u(json, ".bridgeZeta.zeta.c1")),
            uint64(_u(json, ".bridgeZeta.zeta.c2"))
        );
        bridge.claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".bridgeZeta.claimedSum.c0")),
            uint64(_u(json, ".bridgeZeta.claimedSum.c1")),
            uint64(_u(json, ".bridgeZeta.claimedSum.c2"))
        );
        bridge.evalPoint = new GoldilocksExt3.Ext3[](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            string memory prefix = string.concat(".bridgeZeta.evalPoint[", vm.toString(i), "].");
            bridge.evalPoint[i] = GoldilocksExt3.Ext3(
                uint64(_u(json, string.concat(prefix, "c0"))),
                uint64(_u(json, string.concat(prefix, "c1"))),
                uint64(_u(json, string.concat(prefix, "c2")))
            );
        }
        bridge.roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            bridge.roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(".bridgeZeta.roundPolys[", vm.toString(i), "][", vm.toString(j), "].");
                bridge.roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }
    }

    function _parseBridgeGZetaDirect(string memory json)
        internal pure returns (SumcheckBridgeGZetaData memory bridge)
    {
        uint256 numRounds = _u(json, ".bridgeGZeta.numRounds");
        bridge.gZeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".bridgeGZeta.gZeta.c0")),
            uint64(_u(json, ".bridgeGZeta.gZeta.c1")),
            uint64(_u(json, ".bridgeGZeta.gZeta.c2"))
        );
        bridge.claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".bridgeGZeta.claimedSum.c0")),
            uint64(_u(json, ".bridgeGZeta.claimedSum.c1")),
            uint64(_u(json, ".bridgeGZeta.claimedSum.c2"))
        );
        bridge.evalPoint = new GoldilocksExt3.Ext3[](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            string memory prefix = string.concat(".bridgeGZeta.evalPoint[", vm.toString(i), "].");
            bridge.evalPoint[i] = GoldilocksExt3.Ext3(
                uint64(_u(json, string.concat(prefix, "c0"))),
                uint64(_u(json, string.concat(prefix, "c1"))),
                uint64(_u(json, string.concat(prefix, "c2")))
            );
        }
        bridge.roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            bridge.roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(".bridgeGZeta.roundPolys[", vm.toString(i), "][", vm.toString(j), "].");
                bridge.roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }
    }

    function _parseBridgeZeta(string memory json)
        internal pure returns (WhirPlonky2Verifier.SumcheckBridgeData memory bridge)
    {
        uint256 numRounds = _u(json, ".proof.bridgeZeta.numRounds");
        // sessionName is now in VK, not in proof

        bridge.zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".proof.bridgeZeta.zeta.c0")),
            uint64(_u(json, ".proof.bridgeZeta.zeta.c1")),
            uint64(_u(json, ".proof.bridgeZeta.zeta.c2"))
        );

        bridge.claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".proof.bridgeZeta.claimedSum.c0")),
            uint64(_u(json, ".proof.bridgeZeta.claimedSum.c1")),
            uint64(_u(json, ".proof.bridgeZeta.claimedSum.c2"))
        );

        // evalPoint
        bridge.evalPoint = new GoldilocksExt3.Ext3[](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            string memory prefix = string.concat(".proof.bridgeZeta.evalPoint[", vm.toString(i), "].");
            bridge.evalPoint[i] = GoldilocksExt3.Ext3(
                uint64(_u(json, string.concat(prefix, "c0"))),
                uint64(_u(json, string.concat(prefix, "c1"))),
                uint64(_u(json, string.concat(prefix, "c2")))
            );
        }

        // roundPolys
        bridge.roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            bridge.roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(
                    ".proof.bridgeZeta.roundPolys[", vm.toString(i), "][", vm.toString(j), "]."
                );
                bridge.roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }
    }

    function _parseBridgeGZeta(string memory json)
        internal pure returns (WhirPlonky2Verifier.SumcheckBridgeGZetaData memory bridge)
    {
        uint256 numRounds = _u(json, ".proof.bridgeGZeta.numRounds");

        bridge.gZeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".proof.bridgeGZeta.gZeta.c0")),
            uint64(_u(json, ".proof.bridgeGZeta.gZeta.c1")),
            uint64(_u(json, ".proof.bridgeGZeta.gZeta.c2"))
        );

        bridge.claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".proof.bridgeGZeta.claimedSum.c0")),
            uint64(_u(json, ".proof.bridgeGZeta.claimedSum.c1")),
            uint64(_u(json, ".proof.bridgeGZeta.claimedSum.c2"))
        );

        // evalPoint
        bridge.evalPoint = new GoldilocksExt3.Ext3[](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            string memory prefix = string.concat(".proof.bridgeGZeta.evalPoint[", vm.toString(i), "].");
            bridge.evalPoint[i] = GoldilocksExt3.Ext3(
                uint64(_u(json, string.concat(prefix, "c0"))),
                uint64(_u(json, string.concat(prefix, "c1"))),
                uint64(_u(json, string.concat(prefix, "c2")))
            );
        }

        // roundPolys
        bridge.roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            bridge.roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(
                    ".proof.bridgeGZeta.roundPolys[", vm.toString(i), "][", vm.toString(j), "]."
                );
                bridge.roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }
    }

    function _parseCircuitConfig(string memory json)
        internal pure returns (WhirPlonky2Verifier.CircuitConfig memory config)
    {
        config.degreeBits = _u(json, ".circuitConfig.degreeBits");
        config.numChallenges = _u(json, ".circuitConfig.numChallenges");
        config.numRoutedWires = _u(json, ".circuitConfig.numRoutedWires");
        config.quotientDegreeFactor = _u(json, ".circuitConfig.quotientDegreeFactor");
        config.numPartialProducts = _u(json, ".circuitConfig.numPartialProducts");
        config.numGateConstraints = _u(json, ".circuitConfig.numGateConstraints");
        config.numSelectors = _u(json, ".circuitConfig.numSelectors");
        config.numLookupSelectors = _u(json, ".circuitConfig.numLookupSelectors");
        config.batchSizes = abi.decode(vm.parseJson(json, ".circuitConfig.batchSizes"), (uint256[]));
        config.intraBatchPolyCounts = abi.decode(vm.parseJson(json, ".circuitConfig.intraBatchPolyCounts"), (uint256[]));
        config.sessionName = abi.decode(vm.parseJson(json, ".circuitConfig.sessionName"), (string));

        // Parse gates
        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".circuitConfig.gates..gateType"), (uint256[]));
        config.gates = _parseGatesFromConfig(json, gateTypes.length);

        // Parse permutation
        config.permutation.kIs = abi.decode(vm.parseJson(json, ".circuitConfig.permutation.kIs"), (uint256[]));
    }

    function _parseGatesFromConfig(string memory json, uint256 numGates)
        internal pure returns (GateInfo[] memory)
    {
        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".circuitConfig.gates..gateType"), (uint256[]));
        uint256[] memory selectorIndices = abi.decode(vm.parseJson(json, ".circuitConfig.gates..selectorIndex"), (uint256[]));
        uint256[] memory groupStarts = abi.decode(vm.parseJson(json, ".circuitConfig.gates..groupStart"), (uint256[]));
        uint256[] memory groupEnds = abi.decode(vm.parseJson(json, ".circuitConfig.gates..groupEnd"), (uint256[]));
        uint256[] memory rowInGroups = abi.decode(vm.parseJson(json, ".circuitConfig.gates..rowInGroup"), (uint256[]));
        uint256[] memory numConstraintsList = abi.decode(vm.parseJson(json, ".circuitConfig.gates..numConstraints"), (uint256[]));

        GateInfo[] memory gates = new GateInfo[](numGates);
        for (uint256 i = 0; i < numGates; i++) {
            string memory cfgKey = string.concat(".circuitConfig.gates[", vm.toString(i), "].gateConfig");
            uint256[] memory cfg = abi.decode(vm.parseJson(json, cfgKey), (uint256[]));
            gates[i] = GateInfo(
                gateTypes[i], selectorIndices[i], groupStarts[i],
                groupEnds[i], rowInGroups[i], numConstraintsList[i],
                cfg
            );
        }
        return gates;
    }

    /// @dev Load WhirParams from VK JSON. evaluationPoint/evaluationPoint2 are empty
    ///      (they come from the proof, set during verify via _loadWhirParams).
    function _loadWhirParamsFromVK(string memory json)
        internal pure returns (SpongefishWhirVerify.WhirParams memory p)
    {
        p.numVariables = _u(json, ".whirParams.num_variables");
        p.foldingFactor = _u(json, ".whirParams.folding_factor");
        p.numVectors = _u(json, ".whirParams.num_vectors");
        p.outDomainSamples = _u(json, ".whirParams.out_domain_samples");
        p.inDomainSamples = _u(json, ".whirParams.in_domain_samples");
        p.initialSumcheckRounds = _u(json, ".whirParams.initial_sumcheck_rounds");
        p.numRounds = _u(json, ".whirParams.num_rounds");
        p.finalSumcheckRounds = _u(json, ".whirParams.final_sumcheck_rounds");
        p.finalSize = _u(json, ".whirParams.final_size");
        p.initialCodewordLength = _u(json, ".whirParams.initial_codeword_length");
        p.initialMerkleDepth = _u(json, ".whirParams.initial_merkle_depth");
        p.initialDomainGenerator = uint64(_u(json, ".whirParams.initial_domain_generator"));
        p.initialInterleavingDepth = _u(json, ".whirParams.initial_interleaving_depth");
        p.initialNumVariables = _u(json, ".whirParams.initial_num_variables");
        p.initialCosetSize = _u(json, ".whirParams.initial_coset_size");
        p.initialNumCosets = _u(json, ".whirParams.initial_num_cosets");
        // evaluationPoint and evaluationPoint2 are left empty —
        // they are per-proof (sumcheck-derived) and set in verify()
        p.rounds = new SpongefishWhirVerify.RoundParams[](p.numRounds);
        for (uint256 i = 0; i < p.numRounds; i++) {
            string memory prefix = string.concat(".whirParams.rounds[", vm.toString(i), "].");
            p.rounds[i].codewordLength = _u(json, string.concat(prefix, "codeword_length"));
            p.rounds[i].merkleDepth = _u(json, string.concat(prefix, "merkle_depth"));
            p.rounds[i].domainGenerator = uint64(_u(json, string.concat(prefix, "domain_generator")));
            p.rounds[i].inDomainSamples = _u(json, string.concat(prefix, "in_domain_samples"));
            p.rounds[i].outDomainSamples = _u(json, string.concat(prefix, "out_domain_samples"));
            p.rounds[i].sumcheckRounds = _u(json, string.concat(prefix, "sumcheck_rounds"));
            p.rounds[i].interleavingDepth = _u(json, string.concat(prefix, "interleaving_depth"));
            p.rounds[i].cosetSize = _u(json, string.concat(prefix, "coset_size"));
            p.rounds[i].numCosets = _u(json, string.concat(prefix, "num_cosets"));
            p.rounds[i].numVariables = _u(json, string.concat(prefix, "num_variables"));
        }
    }

    function _loadUnifiedWhirParams(
        string memory json,
        WhirPlonky2Verifier.Proof memory proof
    ) internal pure returns (SpongefishWhirVerify.WhirParams memory p) {
        p.numVariables = _u(json, ".whirParams.num_variables");
        p.foldingFactor = _u(json, ".whirParams.folding_factor");
        p.numVectors = _u(json, ".whirParams.num_vectors");
        p.outDomainSamples = _u(json, ".whirParams.out_domain_samples");
        p.inDomainSamples = _u(json, ".whirParams.in_domain_samples");
        p.initialSumcheckRounds = _u(json, ".whirParams.initial_sumcheck_rounds");
        p.numRounds = _u(json, ".whirParams.num_rounds");
        p.finalSumcheckRounds = _u(json, ".whirParams.final_sumcheck_rounds");
        p.finalSize = _u(json, ".whirParams.final_size");
        p.initialCodewordLength = _u(json, ".whirParams.initial_codeword_length");
        p.initialMerkleDepth = _u(json, ".whirParams.initial_merkle_depth");
        p.initialDomainGenerator = uint64(_u(json, ".whirParams.initial_domain_generator"));
        p.initialInterleavingDepth = _u(json, ".whirParams.initial_interleaving_depth");
        p.initialNumVariables = _u(json, ".whirParams.initial_num_variables");
        p.initialCosetSize = _u(json, ".whirParams.initial_coset_size");
        p.initialNumCosets = _u(json, ".whirParams.initial_num_cosets");

        // Evaluation points from bridge data (already parsed in proof)
        {
            uint256 nv = p.numVariables;
            p.evaluationPoint = new GoldilocksExt3.Ext3[](nv);
            for (uint256 i = 0; i < nv; i++) {
                string memory epPrefix = string.concat(".proof.bridgeZeta.evalPoint[", vm.toString(i), "].");
                p.evaluationPoint[i] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(epPrefix, "c0"))),
                    uint64(_u(json, string.concat(epPrefix, "c1"))),
                    uint64(_u(json, string.concat(epPrefix, "c2")))
                );
            }
        }

        // Second evaluation point for g*zeta bridge
        {
            uint256 nv = p.numVariables;
            p.evaluationPoint2 = new GoldilocksExt3.Ext3[](nv);
            for (uint256 i = 0; i < nv; i++) {
                string memory epPrefix = string.concat(".proof.bridgeGZeta.evalPoint[", vm.toString(i), "].");
                p.evaluationPoint2[i] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(epPrefix, "c0"))),
                    uint64(_u(json, string.concat(epPrefix, "c1"))),
                    uint64(_u(json, string.concat(epPrefix, "c2")))
                );
            }
        }

        // Rounds
        p.rounds = new SpongefishWhirVerify.RoundParams[](p.numRounds);
        for (uint256 i = 0; i < p.numRounds; i++) {
            string memory prefix = string.concat(".whirParams.rounds[", vm.toString(i), "].");
            p.rounds[i].codewordLength = _u(json, string.concat(prefix, "codeword_length"));
            p.rounds[i].merkleDepth = _u(json, string.concat(prefix, "merkle_depth"));
            p.rounds[i].domainGenerator = uint64(_u(json, string.concat(prefix, "domain_generator")));
            p.rounds[i].inDomainSamples = _u(json, string.concat(prefix, "in_domain_samples"));
            p.rounds[i].outDomainSamples = _u(json, string.concat(prefix, "out_domain_samples"));
            p.rounds[i].sumcheckRounds = _u(json, string.concat(prefix, "sumcheck_rounds"));
            p.rounds[i].interleavingDepth = _u(json, string.concat(prefix, "interleaving_depth"));
            p.rounds[i].cosetSize = _u(json, string.concat(prefix, "coset_size"));
            p.rounds[i].numCosets = _u(json, string.concat(prefix, "num_cosets"));
            p.rounds[i].numVariables = _u(json, string.concat(prefix, "num_variables"));
        }
    }
}
