// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, console} from "forge-std/Test.sol";
import {SpongefishWhirVerify} from "../src/spongefish/SpongefishWhirVerify.sol";
import {GoldilocksExt3} from "../src/spongefish/GoldilocksExt3.sol";
import {SumcheckBridgeVerifier} from "../src/spongefish/SumcheckBridgeVerifier.sol";
import {Plonky2Verifier} from "../src/Plonky2Verifier.sol";
import {GoldilocksField, GoldilocksExt2} from "../src/GoldilocksField.sol";

/// @title GenericE2ETest
/// @notice E2E test using a generic Poseidon hash-chain circuit (no intmax3 dependency).
///         Fixtures are generated by `cargo run --bin generate_fixture --release`.
///         Verifies WHIR polynomial commitment + Plonky2 constraint satisfaction on-chain.
contract GenericE2ETest is Test, Plonky2Verifier {

    // =====================================================================
    // WHIR combined verification
    // =====================================================================

    function test_whir_combined() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        _verifyWhirCommitment(json);
    }

    // =====================================================================
    // Plonky2 constraint satisfaction
    // =====================================================================

    function test_plonky2_constraints() public {
        string memory json = vm.readFile("test/data/test_constraint_data.json");
        _verifyPlonky2Constraints(json);
    }

    // =====================================================================
    // Combined E2E
    // =====================================================================

    function test_full_e2e() public {
        string memory whirJson = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        string memory constraintJson = vm.readFile("test/data/test_constraint_data.json");

        // 1. WHIR polynomial commitment verification
        {
            uint256 gasBefore = gasleft();
            _verifyWhirCommitment(whirJson);
            console.log("WHIR combined gas:", gasBefore - gasleft());
        }

        // 2. Sumcheck bridge — binding between WHIR commitment and constraint openings
        {
            uint256 gasBefore = gasleft();
            _verifySumcheckBridge(whirJson);
            console.log("Sumcheck bridge gas:", gasBefore - gasleft());
        }

        // 3. On-chain challenge re-derivation (Keccak)
        {
            uint256 gasBefore = gasleft();
            _verifyChallengeDerivation(whirJson, constraintJson);
            console.log("Challenge derivation gas:", gasBefore - gasleft());
        }

        // 4. Opening decomposition check
        {
            uint256 gasBefore = gasleft();
            _verifyDecomposition(whirJson, constraintJson);
            console.log("Decomposition gas:", gasBefore - gasleft());
        }

        // 5. Plonky2 constraints
        {
            uint256 gasBefore = gasleft();
            _verifyPlonky2Constraints(constraintJson);
            console.log("Plonky2 constraints gas:", gasBefore - gasleft());
        }
    }

    // =====================================================================
    // Standalone sumcheck bridge test
    // =====================================================================

    function test_sumcheck_bridge() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        _verifySumcheckBridge(json);
    }

    function test_challenge_derivation() public view {
        string memory whirJson = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        string memory constraintJson = vm.readFile("test/data/test_constraint_data.json");
        _verifyChallengeDerivation(whirJson, constraintJson);
    }

    function test_decomposition() public view {
        string memory whirJson = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        string memory constraintJson = vm.readFile("test/data/test_constraint_data.json");
        _verifyDecomposition(whirJson, constraintJson);
    }

    /// @notice Negative test: tampered claimed_sum must fail
    function test_sumcheck_bridge_tampered_claim() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        uint256 numRounds = _u(json, ".sumcheck.num_rounds");
        string memory sessionName = abi.decode(vm.parseJson(json, ".sumcheck.session_name"), (string));
        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.zeta.c0")),
            uint64(_u(json, ".sumcheck.zeta.c1")),
            uint64(_u(json, ".sumcheck.zeta.c2"))
        );
        // Tamper with claimed_sum: add 1 to c0
        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.claimed_sum.c0")) + 1,
            uint64(_u(json, ".sumcheck.claimed_sum.c1")),
            uint64(_u(json, ".sumcheck.claimed_sum.c2"))
        );
        GoldilocksExt3.Ext3[][] memory roundPolys = _parseSumcheckRoundPolys(json, numRounds);

        bool reverted = false;
        try this._externalVerifyBridge(numRounds, roundPolys, zeta, claimedSum, sessionName) {
            // Should not reach here
        } catch {
            reverted = true;
        }
        assertTrue(reverted, "tampered claimed_sum must revert");
    }

    /// @notice Negative test: tampered round polynomial must fail binding
    function test_sumcheck_bridge_tampered_roundpoly() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        uint256 numRounds = _u(json, ".sumcheck.num_rounds");
        string memory sessionName = abi.decode(vm.parseJson(json, ".sumcheck.session_name"), (string));
        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.zeta.c0")),
            uint64(_u(json, ".sumcheck.zeta.c1")),
            uint64(_u(json, ".sumcheck.zeta.c2"))
        );
        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.claimed_sum.c0")),
            uint64(_u(json, ".sumcheck.claimed_sum.c1")),
            uint64(_u(json, ".sumcheck.claimed_sum.c2"))
        );
        GoldilocksExt3.Ext3[][] memory roundPolys = _parseSumcheckRoundPolys(json, numRounds);

        // Tamper with g(2) in round 5
        roundPolys[5][2].c0 += 1;

        bool reverted = false;
        try this._externalVerifyBridge(numRounds, roundPolys, zeta, claimedSum, sessionName) {
            // Should not reach here
        } catch {
            reverted = true;
        }
        assertTrue(reverted, "tampered round polynomial must revert");
    }

    /// @dev External wrapper for try/catch (internal library calls can't be caught)
    function _externalVerifyBridge(
        uint256 numRounds,
        GoldilocksExt3.Ext3[][] memory roundPolys,
        GoldilocksExt3.Ext3 memory zeta,
        GoldilocksExt3.Ext3 memory claimedSum,
        string memory sessionName
    ) external pure {
        SumcheckBridgeVerifier.verify(numRounds, roundPolys, zeta, claimedSum, sessionName);
    }

    // =====================================================================
    // Internal: Sumcheck bridge verification
    // =====================================================================

    function _verifySumcheckBridge(string memory json) internal pure {
        // Parse sumcheck proof data
        uint256 numRounds = _u(json, ".sumcheck.num_rounds");
        string memory sessionName = abi.decode(vm.parseJson(json, ".sumcheck.session_name"), (string));

        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.zeta.c0")),
            uint64(_u(json, ".sumcheck.zeta.c1")),
            uint64(_u(json, ".sumcheck.zeta.c2"))
        );

        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(json, ".sumcheck.claimed_sum.c0")),
            uint64(_u(json, ".sumcheck.claimed_sum.c1")),
            uint64(_u(json, ".sumcheck.claimed_sum.c2"))
        );

        // Parse round polynomials
        GoldilocksExt3.Ext3[][] memory roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(
                    ".sumcheck.round_polys[", vm.toString(i), "][", vm.toString(j), "]."
                );
                roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }

        // Verify sumcheck: derive evalPoint and finalClaim
        (
            GoldilocksExt3.Ext3[] memory evalPoint,
            GoldilocksExt3.Ext3 memory finalClaim
        ) = SumcheckBridgeVerifier.verify(numRounds, roundPolys, zeta, claimedSum, sessionName);

        // Verify that derived evalPoint matches the one passed to WHIR
        for (uint256 i = 0; i < numRounds; i++) {
            string memory epPrefix = string.concat(".evaluation_point[", vm.toString(i), "].");
            uint64 ec0 = uint64(_u(json, string.concat(epPrefix, "c0")));
            uint64 ec1 = uint64(_u(json, string.concat(epPrefix, "c1")));
            uint64 ec2 = uint64(_u(json, string.concat(epPrefix, "c2")));
            require(
                evalPoint[i].c0 == ec0 && evalPoint[i].c1 == ec1 && evalPoint[i].c2 == ec2,
                string.concat("evalPoint mismatch at round ", vm.toString(i))
            );
        }

        // Compute h_ζ(r)
        GoldilocksExt3.Ext3 memory hZetaAtR = SumcheckBridgeVerifier.computeHZeta(zeta, evalPoint);

        // Get WHIR evaluation f(r) from fixture
        GoldilocksExt3.Ext3 memory whirEvalAtR = GoldilocksExt3.Ext3(
            uint64(_u(json, ".evaluations[0].c0")),
            uint64(_u(json, ".evaluations[0].c1")),
            uint64(_u(json, ".evaluations[0].c2"))
        );

        // Verify binding: f(r) · h_ζ(r) == finalClaim
        SumcheckBridgeVerifier.verifyBinding(whirEvalAtR, hZetaAtR, finalClaim);
    }

    // =====================================================================
    // Internal: Challenge re-derivation (Issue 1 fix)
    // =====================================================================

    function _verifyChallengeDerivation(string memory whirJson, string memory constraintJson) internal pure {
        bytes memory transcript = vm.parseJsonBytes(whirJson, ".transcript");
        uint256[] memory publicInputs = abi.decode(vm.parseJson(constraintJson, ".publicInputs"), (uint256[]));
        uint256 numChallenges = _u(constraintJson, ".circuitParams.numChallenges");

        // Derive challenges on-chain
        (
            uint256[] memory betas,
            uint256[] memory gammas,
            uint256[] memory alphas,
            uint256 zetaC0,
            uint256 zetaC1,
            uint256 zetaC2
        ) = SumcheckBridgeVerifier.deriveKeccakChallenges(transcript, publicInputs, numChallenges);

        // Compare with fixture values
        uint256[] memory expectedBetas = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkBetas"), (uint256[]));
        uint256[] memory expectedGammas = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkGammas"), (uint256[]));
        uint256[] memory expectedAlphas = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkAlphas"), (uint256[]));
        uint256[] memory expectedZeta = abi.decode(vm.parseJson(constraintJson, ".challenges.plonkZeta"), (uint256[]));

        for (uint256 i = 0; i < numChallenges; i++) {
            require(betas[i] == expectedBetas[i], "beta mismatch");
            require(gammas[i] == expectedGammas[i], "gamma mismatch");
            require(alphas[i] == expectedAlphas[i], "alpha mismatch");
        }
        require(zetaC0 == expectedZeta[0], "zeta.c0 mismatch");
        require(zetaC1 == expectedZeta[1], "zeta.c1 mismatch");
        require(zetaC2 == expectedZeta[2], "zeta.c2 mismatch");
    }

    // =====================================================================
    // Internal: Decomposition check (Issue 2 fix)
    // =====================================================================

    function _verifyDecomposition(string memory whirJson, string memory constraintJson) internal pure {
        // Get claimed_sum from sumcheck
        GoldilocksExt3.Ext3 memory claimedSum = GoldilocksExt3.Ext3(
            uint64(_u(whirJson, ".sumcheck.claimed_sum.c0")),
            uint64(_u(whirJson, ".sumcheck.claimed_sum.c1")),
            uint64(_u(whirJson, ".sumcheck.claimed_sum.c2"))
        );

        // Get sumcheck zeta
        GoldilocksExt3.Ext3 memory zeta = GoldilocksExt3.Ext3(
            uint64(_u(whirJson, ".sumcheck.zeta.c0")),
            uint64(_u(whirJson, ".sumcheck.zeta.c1")),
            uint64(_u(whirJson, ".sumcheck.zeta.c2"))
        );

        // Get batch sizes
        uint256[] memory batchSizes = abi.decode(vm.parseJson(constraintJson, ".batchSizes"), (uint256[]));

        // Get batch evaluations at sumcheck.zeta
        uint256 nBatches = batchSizes.length;
        GoldilocksExt3.Ext3[] memory batchEvals = new GoldilocksExt3.Ext3[](nBatches);
        for (uint256 i = 0; i < nBatches; i++) {
            string memory prefix = string.concat(".batchEvalsAtZeta[", vm.toString(i), "].");
            batchEvals[i] = GoldilocksExt3.Ext3(
                uint64(_u(constraintJson, string.concat(prefix, "c0"))),
                uint64(_u(constraintJson, string.concat(prefix, "c1"))),
                uint64(_u(constraintJson, string.concat(prefix, "c2")))
            );
        }

        // Verify: P(ζ) = Σ batch_i(ζ) · ζ^offset_i
        SumcheckBridgeVerifier.verifyDecomposition(claimedSum, batchSizes, zeta, batchEvals);
    }

    // =====================================================================
    // Internal: WHIR commitment verification
    // =====================================================================

    function _verifyWhirCommitment(string memory json) internal pure {
        bytes memory protocolId = vm.parseJsonBytes(json, ".protocol_id");
        bytes memory sessionId = vm.parseJsonBytes(json, ".session_id");
        bytes memory instance = vm.parseJsonBytes(json, ".instance");
        bytes memory transcript = vm.parseJsonBytes(json, ".transcript");
        bytes memory hints = vm.parseJsonBytes(json, ".hints");

        GoldilocksExt3.Ext3[] memory evaluations = new GoldilocksExt3.Ext3[](1);
        {
            uint64 c0 = uint64(abi.decode(vm.parseJson(json, ".evaluations[0].c0"), (uint256)));
            uint64 c1 = uint64(abi.decode(vm.parseJson(json, ".evaluations[0].c1"), (uint256)));
            uint64 c2 = uint64(abi.decode(vm.parseJson(json, ".evaluations[0].c2"), (uint256)));
            evaluations[0] = GoldilocksExt3.Ext3(c0, c1, c2);
        }

        SpongefishWhirVerify.WhirParams memory params = _loadParams(json);

        bool valid = SpongefishWhirVerify.verifyWhirProof(
            protocolId, sessionId, instance, transcript, hints, evaluations, params
        );
        assertTrue(valid, "WHIR combined must verify");
    }

    // =====================================================================
    // Internal: Plonky2 constraint verification
    // =====================================================================

    function _verifyPlonky2Constraints(string memory json) internal {
        CircuitParams memory params;
        params.degreeBits = abi.decode(vm.parseJson(json, ".circuitParams.degreeBits"), (uint256));
        params.numChallenges = abi.decode(vm.parseJson(json, ".circuitParams.numChallenges"), (uint256));
        params.numRoutedWires = abi.decode(vm.parseJson(json, ".circuitParams.numRoutedWires"), (uint256));
        params.quotientDegreeFactor = abi.decode(vm.parseJson(json, ".circuitParams.quotientDegreeFactor"), (uint256));
        params.numPartialProducts = abi.decode(vm.parseJson(json, ".circuitParams.numPartialProducts"), (uint256));
        params.numGateConstraints = abi.decode(vm.parseJson(json, ".circuitParams.numGateConstraints"), (uint256));
        params.numSelectors = abi.decode(vm.parseJson(json, ".circuitParams.numSelectors"), (uint256));
        params.numLookupSelectors = abi.decode(vm.parseJson(json, ".circuitParams.numLookupSelectors"), (uint256));

        uint256[] memory constFlat = abi.decode(vm.parseJson(json, ".openings.constants"), (uint256[]));
        uint256[] memory sigmaFlat = abi.decode(vm.parseJson(json, ".openings.plonkSigmas"), (uint256[]));
        uint256[] memory wiresFlat = abi.decode(vm.parseJson(json, ".openings.wires"), (uint256[]));
        uint256[] memory zsFlat = abi.decode(vm.parseJson(json, ".openings.plonkZs"), (uint256[]));
        uint256[] memory zsNextFlat = abi.decode(vm.parseJson(json, ".openings.plonkZsNext"), (uint256[]));
        uint256[] memory ppFlat = abi.decode(vm.parseJson(json, ".openings.partialProducts"), (uint256[]));
        uint256[] memory qpFlat = abi.decode(vm.parseJson(json, ".openings.quotientPolys"), (uint256[]));

        Openings memory openings;
        openings.constants = _flatToExt3(constFlat);
        openings.plonkSigmas = _flatToExt3(sigmaFlat);
        openings.wires = _flatToExt3(wiresFlat);
        openings.plonkZs = _flatToExt3(zsFlat);
        openings.plonkZsNext = _flatToExt3(zsNextFlat);
        openings.partialProducts = _flatToExt3(ppFlat);
        openings.quotientPolys = _flatToExt3(qpFlat);

        Challenges memory challenges;
        challenges.plonkBetas = abi.decode(vm.parseJson(json, ".challenges.plonkBetas"), (uint256[]));
        challenges.plonkGammas = abi.decode(vm.parseJson(json, ".challenges.plonkGammas"), (uint256[]));
        challenges.plonkAlphas = abi.decode(vm.parseJson(json, ".challenges.plonkAlphas"), (uint256[]));
        {
            uint256[] memory zetaFlat = abi.decode(vm.parseJson(json, ".challenges.plonkZeta"), (uint256[]));
            challenges.plonkZeta = GoldilocksExt3.Ext3(uint64(zetaFlat[0]), uint64(zetaFlat[1]), uint64(zetaFlat.length > 2 ? zetaFlat[2] : 0));
        }

        PermutationData memory permData;
        permData.kIs = abi.decode(vm.parseJson(json, ".permutation.kIs"), (uint256[]));

        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".gates..gateType"), (uint256[]));
        GateInfo[] memory gates = _parseGates(json, gateTypes.length);

        uint256[] memory publicInputs = abi.decode(vm.parseJson(json, ".publicInputs"), (uint256[]));

        bool valid = verifyConstraints(openings, params, challenges, permData, gates, publicInputs);
        assertTrue(valid, "Plonky2 constraint verification must pass");
    }

    // =====================================================================
    // Helpers
    // =====================================================================

    function _loadParams(string memory json) internal pure returns (SpongefishWhirVerify.WhirParams memory p) {
        p.numVariables = _u(json, ".whir_params.num_variables");
        p.foldingFactor = _u(json, ".whir_params.folding_factor");
        p.numVectors = _u(json, ".whir_params.num_vectors");
        p.outDomainSamples = _u(json, ".whir_params.out_domain_samples");
        p.inDomainSamples = _u(json, ".whir_params.in_domain_samples");
        p.initialSumcheckRounds = _u(json, ".whir_params.initial_sumcheck_rounds");
        p.numRounds = _u(json, ".whir_params.num_rounds");
        p.finalSumcheckRounds = _u(json, ".whir_params.final_sumcheck_rounds");
        p.finalSize = _u(json, ".whir_params.final_size");
        p.initialCodewordLength = _u(json, ".whir_params.initial_codeword_length");
        p.initialMerkleDepth = _u(json, ".whir_params.initial_merkle_depth");
        p.initialDomainGenerator = uint64(_u(json, ".whir_params.initial_domain_generator"));
        p.initialInterleavingDepth = _u(json, ".whir_params.initial_interleaving_depth");
        p.initialNumVariables = _u(json, ".whir_params.initial_num_variables");
        p.initialCosetSize = _u(json, ".whir_params.initial_coset_size");
        p.initialNumCosets = _u(json, ".whir_params.initial_num_cosets");

        // Load evaluation point (sumcheck-derived r, or empty for canonical)
        {
            uint256 nv = p.numVariables;
            p.evaluationPoint = new GoldilocksExt3.Ext3[](nv);
            for (uint256 i = 0; i < nv; i++) {
                string memory epPrefix = string.concat(".evaluation_point[", vm.toString(i), "].");
                uint64 c0 = uint64(_u(json, string.concat(epPrefix, "c0")));
                uint64 c1 = uint64(_u(json, string.concat(epPrefix, "c1")));
                uint64 c2 = uint64(_u(json, string.concat(epPrefix, "c2")));
                p.evaluationPoint[i] = GoldilocksExt3.Ext3(c0, c1, c2);
            }
        }

        p.rounds = new SpongefishWhirVerify.RoundParams[](p.numRounds);
        for (uint256 i = 0; i < p.numRounds; i++) {
            string memory prefix = string.concat(".whir_params.rounds[", vm.toString(i), "].");
            p.rounds[i].codewordLength = _u(json, string.concat(prefix, "codeword_length"));
            p.rounds[i].merkleDepth = _u(json, string.concat(prefix, "merkle_depth"));
            p.rounds[i].domainGenerator = uint64(_u(json, string.concat(prefix, "domain_generator")));
            p.rounds[i].inDomainSamples = _u(json, string.concat(prefix, "in_domain_samples"));
            p.rounds[i].outDomainSamples = _u(json, string.concat(prefix, "out_domain_samples"));
            p.rounds[i].sumcheckRounds = _u(json, string.concat(prefix, "sumcheck_rounds"));
            p.rounds[i].interleavingDepth = _u(json, string.concat(prefix, "interleaving_depth"));
            p.rounds[i].cosetSize = _u(json, string.concat(prefix, "coset_size"));
            p.rounds[i].numCosets = _u(json, string.concat(prefix, "num_cosets"));
            p.rounds[i].numVariables = _u(json, string.concat(prefix, "num_variables"));
        }
    }

    function _parseSumcheckRoundPolys(string memory json, uint256 numRounds)
        internal pure returns (GoldilocksExt3.Ext3[][] memory roundPolys)
    {
        roundPolys = new GoldilocksExt3.Ext3[][](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            roundPolys[i] = new GoldilocksExt3.Ext3[](3);
            for (uint256 j = 0; j < 3; j++) {
                string memory prefix = string.concat(
                    ".sumcheck.round_polys[", vm.toString(i), "][", vm.toString(j), "]."
                );
                roundPolys[i][j] = GoldilocksExt3.Ext3(
                    uint64(_u(json, string.concat(prefix, "c0"))),
                    uint64(_u(json, string.concat(prefix, "c1"))),
                    uint64(_u(json, string.concat(prefix, "c2")))
                );
            }
        }
    }

    function _u(string memory json, string memory path) internal pure returns (uint256) {
        return abi.decode(vm.parseJson(json, path), (uint256));
    }

    function _flatToExt3(uint256[] memory flat) internal pure returns (GoldilocksExt3.Ext3[] memory) {
        uint256 len = flat.length / 3;
        GoldilocksExt3.Ext3[] memory result = new GoldilocksExt3.Ext3[](len);
        for (uint256 i = 0; i < len; i++) {
            result[i] = GoldilocksExt3.Ext3(uint64(flat[i * 3]), uint64(flat[i * 3 + 1]), uint64(flat[i * 3 + 2]));
        }
        return result;
    }

    function _parseGates(string memory json, uint256 numGates)
        internal pure returns (GateInfo[] memory)
    {
        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".gates..gateType"), (uint256[]));
        uint256[] memory selectorIndices = abi.decode(vm.parseJson(json, ".gates..selectorIndex"), (uint256[]));
        uint256[] memory groupStarts = abi.decode(vm.parseJson(json, ".gates..groupStart"), (uint256[]));
        uint256[] memory groupEnds = abi.decode(vm.parseJson(json, ".gates..groupEnd"), (uint256[]));
        uint256[] memory rowInGroups = abi.decode(vm.parseJson(json, ".gates..rowInGroup"), (uint256[]));
        uint256[] memory numConstraintsList = abi.decode(vm.parseJson(json, ".gates..numConstraints"), (uint256[]));

        GateInfo[] memory gates = new GateInfo[](numGates);
        for (uint256 i = 0; i < numGates; i++) {
            // Parse gateConfig from JSON
            string memory cfgKey = string.concat(".gates[", vm.toString(i), "].gateConfig");
            uint256[] memory config = abi.decode(vm.parseJson(json, cfgKey), (uint256[]));
            gates[i] = GateInfo(
                gateTypes[i], selectorIndices[i], groupStarts[i],
                groupEnds[i], rowInGroups[i], numConstraintsList[i],
                config
            );
        }
        return gates;
    }
}
