// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, console} from "forge-std/Test.sol";
import {SpongefishWhirVerify} from "../src/spongefish/SpongefishWhirVerify.sol";
import {GoldilocksExt3} from "../src/spongefish/GoldilocksExt3.sol";
import {Plonky2Verifier} from "../src/Plonky2Verifier.sol";
import {GoldilocksExt2} from "../src/GoldilocksField.sol";

/// @title GenericE2ETest
/// @notice E2E test using a generic Poseidon hash-chain circuit (no intmax3 dependency).
///         Fixtures are generated by `cargo run --bin generate_fixture --release`.
///         Verifies WHIR polynomial commitment + Plonky2 constraint satisfaction on-chain.
contract GenericE2ETest is Test, Plonky2Verifier {

    // =====================================================================
    // WHIR combined verification
    // =====================================================================

    function test_whir_combined() public view {
        string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
        _verifyWhirCommitment(json);
    }

    // =====================================================================
    // Plonky2 constraint satisfaction
    // =====================================================================

    function test_plonky2_constraints() public {
        string memory json = vm.readFile("test/data/test_constraint_data.json");
        _verifyPlonky2Constraints(json);
    }

    // =====================================================================
    // Combined E2E
    // =====================================================================

    function test_full_e2e() public {
        // WHIR
        {
            string memory json = vm.readFile("test/data/whir/test_combined_verifier_data.json");
            uint256 gasBefore = gasleft();
            _verifyWhirCommitment(json);
            console.log("WHIR combined gas:", gasBefore - gasleft());
        }

        // Plonky2 constraints
        {
            string memory json = vm.readFile("test/data/test_constraint_data.json");
            uint256 gasBefore = gasleft();
            _verifyPlonky2Constraints(json);
            console.log("Plonky2 constraints gas:", gasBefore - gasleft());
        }
    }

    // =====================================================================
    // Internal: WHIR commitment verification
    // =====================================================================

    function _verifyWhirCommitment(string memory json) internal pure {
        bytes memory protocolId = vm.parseJsonBytes(json, ".protocol_id");
        bytes memory sessionId = vm.parseJsonBytes(json, ".session_id");
        bytes memory instance = vm.parseJsonBytes(json, ".instance");
        bytes memory transcript = vm.parseJsonBytes(json, ".transcript");
        bytes memory hints = vm.parseJsonBytes(json, ".hints");

        GoldilocksExt3.Ext3[] memory evaluations = new GoldilocksExt3.Ext3[](1);
        {
            uint64 c0 = uint64(abi.decode(vm.parseJson(json, ".evaluations[0].c0"), (uint256)));
            uint64 c1 = uint64(abi.decode(vm.parseJson(json, ".evaluations[0].c1"), (uint256)));
            uint64 c2 = uint64(abi.decode(vm.parseJson(json, ".evaluations[0].c2"), (uint256)));
            evaluations[0] = GoldilocksExt3.Ext3(c0, c1, c2);
        }

        SpongefishWhirVerify.WhirParams memory params = _loadParams(json);

        bool valid = SpongefishWhirVerify.verifyWhirProof(
            protocolId, sessionId, instance, transcript, hints, evaluations, params
        );
        assertTrue(valid, "WHIR combined must verify");
    }

    // =====================================================================
    // Internal: Plonky2 constraint verification
    // =====================================================================

    function _verifyPlonky2Constraints(string memory json) internal {
        CircuitParams memory params;
        params.degreeBits = abi.decode(vm.parseJson(json, ".circuitParams.degreeBits"), (uint256));
        params.numChallenges = abi.decode(vm.parseJson(json, ".circuitParams.numChallenges"), (uint256));
        params.numRoutedWires = abi.decode(vm.parseJson(json, ".circuitParams.numRoutedWires"), (uint256));
        params.quotientDegreeFactor = abi.decode(vm.parseJson(json, ".circuitParams.quotientDegreeFactor"), (uint256));
        params.numPartialProducts = abi.decode(vm.parseJson(json, ".circuitParams.numPartialProducts"), (uint256));
        params.numGateConstraints = abi.decode(vm.parseJson(json, ".circuitParams.numGateConstraints"), (uint256));
        params.numSelectors = abi.decode(vm.parseJson(json, ".circuitParams.numSelectors"), (uint256));
        params.numLookupSelectors = abi.decode(vm.parseJson(json, ".circuitParams.numLookupSelectors"), (uint256));

        uint256[] memory constFlat = abi.decode(vm.parseJson(json, ".openings.constants"), (uint256[]));
        uint256[] memory sigmaFlat = abi.decode(vm.parseJson(json, ".openings.plonkSigmas"), (uint256[]));
        uint256[] memory wiresFlat = abi.decode(vm.parseJson(json, ".openings.wires"), (uint256[]));
        uint256[] memory zsFlat = abi.decode(vm.parseJson(json, ".openings.plonkZs"), (uint256[]));
        uint256[] memory zsNextFlat = abi.decode(vm.parseJson(json, ".openings.plonkZsNext"), (uint256[]));
        uint256[] memory ppFlat = abi.decode(vm.parseJson(json, ".openings.partialProducts"), (uint256[]));
        uint256[] memory qpFlat = abi.decode(vm.parseJson(json, ".openings.quotientPolys"), (uint256[]));

        Openings memory openings;
        openings.constants = _flatToExt2(constFlat);
        openings.plonkSigmas = _flatToExt2(sigmaFlat);
        openings.wires = _flatToExt2(wiresFlat);
        openings.plonkZs = _flatToExt2(zsFlat);
        openings.plonkZsNext = _flatToExt2(zsNextFlat);
        openings.partialProducts = _flatToExt2(ppFlat);
        openings.quotientPolys = _flatToExt2(qpFlat);

        Challenges memory challenges;
        challenges.plonkBetas = abi.decode(vm.parseJson(json, ".challenges.plonkBetas"), (uint256[]));
        challenges.plonkGammas = abi.decode(vm.parseJson(json, ".challenges.plonkGammas"), (uint256[]));
        challenges.plonkAlphas = abi.decode(vm.parseJson(json, ".challenges.plonkAlphas"), (uint256[]));
        {
            uint256[] memory zetaFlat = abi.decode(vm.parseJson(json, ".challenges.plonkZeta"), (uint256[]));
            challenges.plonkZeta = GoldilocksExt2.Ext2(zetaFlat[0], zetaFlat[1]);
        }

        PermutationData memory permData;
        permData.kIs = abi.decode(vm.parseJson(json, ".permutation.kIs"), (uint256[]));

        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".gates..gateType"), (uint256[]));
        GateInfo[] memory gates = _parseGates(json, gateTypes.length);

        uint256[] memory publicInputs = abi.decode(vm.parseJson(json, ".publicInputs"), (uint256[]));

        bool valid = verifyConstraints(openings, params, challenges, permData, gates, publicInputs);
        assertTrue(valid, "Plonky2 constraint verification must pass");
    }

    // =====================================================================
    // Helpers
    // =====================================================================

    function _loadParams(string memory json) internal pure returns (SpongefishWhirVerify.WhirParams memory p) {
        p.numVariables = _u(json, ".whir_params.num_variables");
        p.foldingFactor = _u(json, ".whir_params.folding_factor");
        p.numVectors = _u(json, ".whir_params.num_vectors");
        p.outDomainSamples = _u(json, ".whir_params.out_domain_samples");
        p.inDomainSamples = _u(json, ".whir_params.in_domain_samples");
        p.initialSumcheckRounds = _u(json, ".whir_params.initial_sumcheck_rounds");
        p.numRounds = _u(json, ".whir_params.num_rounds");
        p.finalSumcheckRounds = _u(json, ".whir_params.final_sumcheck_rounds");
        p.finalSize = _u(json, ".whir_params.final_size");
        p.initialCodewordLength = _u(json, ".whir_params.initial_codeword_length");
        p.initialMerkleDepth = _u(json, ".whir_params.initial_merkle_depth");
        p.initialDomainGenerator = uint64(_u(json, ".whir_params.initial_domain_generator"));
        p.initialInterleavingDepth = _u(json, ".whir_params.initial_interleaving_depth");
        p.initialNumVariables = _u(json, ".whir_params.initial_num_variables");
        p.initialCosetSize = _u(json, ".whir_params.initial_coset_size");
        p.initialNumCosets = _u(json, ".whir_params.initial_num_cosets");

        // Load evaluation point (sumcheck-derived r, or empty for canonical)
        {
            uint256 nv = p.numVariables;
            p.evaluationPoint = new GoldilocksExt3.Ext3[](nv);
            for (uint256 i = 0; i < nv; i++) {
                string memory epPrefix = string.concat(".evaluation_point[", vm.toString(i), "].");
                uint64 c0 = uint64(_u(json, string.concat(epPrefix, "c0")));
                uint64 c1 = uint64(_u(json, string.concat(epPrefix, "c1")));
                uint64 c2 = uint64(_u(json, string.concat(epPrefix, "c2")));
                p.evaluationPoint[i] = GoldilocksExt3.Ext3(c0, c1, c2);
            }
        }

        p.rounds = new SpongefishWhirVerify.RoundParams[](p.numRounds);
        for (uint256 i = 0; i < p.numRounds; i++) {
            string memory prefix = string.concat(".whir_params.rounds[", vm.toString(i), "].");
            p.rounds[i].codewordLength = _u(json, string.concat(prefix, "codeword_length"));
            p.rounds[i].merkleDepth = _u(json, string.concat(prefix, "merkle_depth"));
            p.rounds[i].domainGenerator = uint64(_u(json, string.concat(prefix, "domain_generator")));
            p.rounds[i].inDomainSamples = _u(json, string.concat(prefix, "in_domain_samples"));
            p.rounds[i].outDomainSamples = _u(json, string.concat(prefix, "out_domain_samples"));
            p.rounds[i].sumcheckRounds = _u(json, string.concat(prefix, "sumcheck_rounds"));
            p.rounds[i].interleavingDepth = _u(json, string.concat(prefix, "interleaving_depth"));
            p.rounds[i].cosetSize = _u(json, string.concat(prefix, "coset_size"));
            p.rounds[i].numCosets = _u(json, string.concat(prefix, "num_cosets"));
            p.rounds[i].numVariables = _u(json, string.concat(prefix, "num_variables"));
        }
    }

    function _u(string memory json, string memory path) internal pure returns (uint256) {
        return abi.decode(vm.parseJson(json, path), (uint256));
    }

    function _flatToExt2(uint256[] memory flat) internal pure returns (GoldilocksExt2.Ext2[] memory) {
        uint256 len = flat.length / 2;
        GoldilocksExt2.Ext2[] memory result = new GoldilocksExt2.Ext2[](len);
        for (uint256 i = 0; i < len; i++) {
            result[i] = GoldilocksExt2.Ext2(flat[i * 2], flat[i * 2 + 1]);
        }
        return result;
    }

    function _parseGates(string memory json, uint256 numGates)
        internal pure returns (GateInfo[] memory)
    {
        uint256[] memory gateTypes = abi.decode(vm.parseJson(json, ".gates..gateType"), (uint256[]));
        uint256[] memory selectorIndices = abi.decode(vm.parseJson(json, ".gates..selectorIndex"), (uint256[]));
        uint256[] memory groupStarts = abi.decode(vm.parseJson(json, ".gates..groupStart"), (uint256[]));
        uint256[] memory groupEnds = abi.decode(vm.parseJson(json, ".gates..groupEnd"), (uint256[]));
        uint256[] memory rowInGroups = abi.decode(vm.parseJson(json, ".gates..rowInGroup"), (uint256[]));
        uint256[] memory numConstraintsList = abi.decode(vm.parseJson(json, ".gates..numConstraints"), (uint256[]));

        GateInfo[] memory gates = new GateInfo[](numGates);
        for (uint256 i = 0; i < numGates; i++) {
            // Parse gateConfig from JSON
            string memory cfgKey = string.concat(".gates[", vm.toString(i), "].gateConfig");
            uint256[] memory config = abi.decode(vm.parseJson(json, cfgKey), (uint256[]));
            gates[i] = GateInfo(
                gateTypes[i], selectorIndices[i], groupStarts[i],
                groupEnds[i], rowInGroups[i], numConstraintsList[i],
                config
            );
        }
        return gates;
    }
}
